### DISCUSSION TITLE
Welcome to bugster-cli Discussions!

### DISCUSSION THREAD

**Discussion by akabarki76** [AKA-NETWORK/bugster-cli#2] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by akabarki76** [comment]
Absolutely! Let's generate your first test spec for **login functionality** since you've already set up credentials. This is a common starting point and will validate your Bugster configuration.

### Here's a sample `login_spec.yaml` for your project:
```yaml
# tests/login_spec.yaml
name: "Login Functionality Test"
description: "Validate successful authentication flow"
baseUrl: "{{config.baseUrl}}"  # Uses your configured http://localhost:3000

scenarios:
  - name: "Login with valid credentials"
    steps:
      - action: "navigate"
        url: "/login"
        validate:
          - title: "Login Page"
      
      - action: "fill"
        target: "#username"  # Update selector to match your UI
        value: "{{credentials.akabarki76.username}}"
        
      - action: "fill"
        target: "#password"  # Update selector to match your UI
        value: "{{credentials.akabarki76.password}}"
        
      - action: "click"
        target: "#submit-btn"  # Update selector to match your UI
        
      - action: "validate"
        assertions:
          - url: "/dashboard"
          - elementPresent: ".welcome-message"
          - textContains: ".user-greeting" "Welcome, {{credentials.akabarki76.username}}"

  - name: "Login with invalid credentials"
    steps:
      - action: "navigate"
        url: "/login"
        
      - action: "fill"
        target: "#username"
        value: "invalid@email.com"
        
      - action: "fill"
        target: "#password"
        value: "wrong_password"
        
      - action: "click"
        target: "#submit-btn"
        
      - action: "validate"
        assertions:
          - elementPresent: ".error-message"
          - textContains: ".error-message" "Invalid credentials"
```

### Key features of this spec:
1. **Real credential usage**: References your `akabarki76` credentials from `config.yaml`
2. **Two scenarios**: Valid and invalid login cases
3. **Automatic base URL**: Uses your configured `http://localhost:3000`
4. **Validation points**: Checks URL changes, element presence, and content

### Before running:
1. **Update CSS selectors** (marked with comments) to match your actual UI elements
2. **Create the file at**:  
   `C:\Users\start\bugster-cli\tests\login_spec.yaml`

### To execute:
```bash
bugster run tests/login_spec.yaml
```

### Want me to:
1. Explain how to customize this spec for your specific login page?
2. Show how to handle 2FA or other auth complexities?
3. Create a spec for another part of your application (e.g., signup or profile)?
4. Explain the Bugster assertion syntax in more detail?

Just point me in the direction you want to go next! 🚀
